pipeline fix

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -2,10 +2,13 @@ name: Main
 
 on:
   push:
-    branches: [1.x]
+    branches:
+      - 1.x
+      - main
   pull_request:
-    branches: [1.x]
-
+    branches:
+      - 1.x
+      - main
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -34,7 +37,7 @@ jobs:
         run: |
           echo "${{ secrets.ENV_TESTING }}" > .env
 
-      - name: Install Sail
+      - name: Install
         run: |
           docker run --rm \
           -u "$(id -u):$(id -g)" \
@@ -56,9 +59,10 @@ jobs:
         run: |
           echo "Waiting for App to start on port 80..."
 
-            while ! curl --output /dev/null --silent --head --fail http://0.0.0.0:80; do
-              sleep 1 && echo -n '.';
-            done;
+            sleep 60;
+            # while ! curl --output /dev/null --silent --head --fail http://0.0.0.0:80; do
+            #   sleep 1 && echo -n '.';
+            # done;
 
           echo "App started"
           exit;
@@ -77,19 +81,19 @@ jobs:
       - name: E2E Tests
         run: vendor/bin/sail dusk
 
-      # - name: Upload Screenshots
-      #   if: failure()
-      #   uses: actions/upload-artifact@v4
-      #   with:
-      #     name: screenshots
-      #     path: tests/Browser/screenshots
+      - name: Upload Screenshots
+        if: failure()
+        uses: actions/upload-artifact@v4
+        with:
+          name: screenshots
+          path: tests/Browser/screenshots
 
-      # - name: Upload Console Logs
-      #   if: failure()
-      #   uses: actions/upload-artifact@v4
-      #   with:
-      #     name: console
-      #     path: tests/Browser/console
+      - name: Upload Console Logs
+        if: failure()
+        uses: actions/upload-artifact@v4
+        with:
+          name: console
+          path: tests/Browser/console
 
       - name: Shut down containers
         if: always()
