minor fix

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -58,9 +58,10 @@ jobs:
         run: |
           echo "Waiting for App to start on port 80..."
 
-          while ! curl --output /dev/null --silent --head --fail http://0.0.0.0:80; do
-            sleep 10 && docker container ls --all;
-          done;
+          sleep 360
+          # while ! curl --output /dev/null --silent --head --fail http://0.0.0.0:80; do
+          #   sleep 10 && docker container ls --all;
+          # done;
 
           echo "App started"
           exit;
